#!/bin/bash

resolution=150
output=~/Downloads/scan.pdf
multiple=false
verbose=false
debug=false

function usage () {
    echo "Scan to file (pdf)"
    echo "Options :"
    echo "  -r                : Resolution. Defaults to $resolution"
    echo "  -o <output_file>  : Set output file. Defaults to $output"
    echo "  -m                : Multiple"
    echo "  -v                : Verbose"
    echo "  -d                : Debug"
}

# Parameters : (output (str))
function scan_pdf () {
    if [ "$debug" = false ]; then
        scanimage --resolution $resolution -x 210 -y 295 --format tiff > /tmp/scan.tiff
        convert -rotate 180 /tmp/scan.tiff $1
    else
        echo "scanimage --resolution $resolution -x 210 -y 295 --format tiff > /tmp/scan.tiff"
        echo "convert -rotate 180 /tmp/scan.tiff $1"
    fi
}

while getopts r:o:mvdh flag
do
    case "${flag}" in
        r) resolution=${OPTARG};;
        o) output=${OPTARG};;
        m) multiple=true;;
        v) verbose=true;;
        d) debug=true;;
        h) usage; exit 0;;
    esac
done

echo "Scanning to file (pdf)"

if [ "$verbose" = true ]; then
    echo "Resolution = $resolution"
    echo "Output = $output"
fi

date=$(date '+%Y-%m-%d-%H-%M-%S')

if [ "$multiple" = true ]; then
    continue=true
    page_nb=1
    while [ "$continue" = true ]; do
        echo "Scanning page $page_nb"
        scan_pdf /tmp/scan_${date}_${page_nb}.pdf
        echo "Scan page $page_nb complete"
        page_nb=$((page_nb+1))

        read -p "Scan another page ? (y/n) : " continue
        if [ "$continue" = "n" ]; then
            continue=false
            break
        else
            continue=true
        fi
    done

    if [ "$debug" = false ]; then
        pdftk /tmp/scan_${date}_*.pdf cat output /tmp/scan_${date}.pdf
        ps2pdf /tmp/scan_${date}.pdf $output
    else
        echo "pdftk /tmp/scan_${date}_*.pdf cat output /tmp/scan_${date}.pdf"
        echo "ps2pdf /tmp/scan_${date}.pdf $output"
    fi

    echo "Scan complete ($page_nb pages). Output = $output"
else
    scan_pdf $output
    echo "Scan complete. Output = $output"
fi

