#!/bin/bash

resolution=150
output=~/Downloads/scan.pdf
gray=false
multiple=false
verbose=false
debug=false

function usage () {
    echo "Scan to file (pdf)"
    echo "Options :"
    echo "  -r                : Resolution. Defaults to $resolution"
    echo "  -o <output_file>  : Set output file. Defaults to $output"
    echo "  -g                : Gray colorspace"
    echo "  -m                : Multiple"
    echo "  -v                : Verbose"
    echo "  -d                : Debug"
}

function scan_pdf () {
    _output=$1

    if [ "$debug" = true ]; then
        echo "scan_pdf(output=$_output)"
    fi

    cmd=(scanimage --resolution $resolution -x 210 -y 295 --format tiff)
    if [ "$debug" = true ]; then
        echo "${cmd[*]} > /tmp/scan.tiff"
    fi
    ${cmd[@]} > /tmp/scan.tiff

    cmd=(convert -rotate 180)
    if [ "$gray" = true ]; then
        cmd+=(-colorspace Gray)
    fi
    cmd+=(/tmp/scan.tiff $_output)
    if [ "$debug" = true ]; then
        echo "${cmd[*]}"
    fi
    ${cmd[@]}
}

while getopts r:o:gmvdh flag
do
    case "${flag}" in
        r) resolution=${OPTARG};;
        o) output=${OPTARG};;
        g) gray=true;;
        m) multiple=true;;
        v) verbose=true;;
        d) debug=true;;
        h) usage; exit 0;;
    esac
done

echo "Scanning to file (pdf)"

if [ "$verbose" = true ]; then
    echo "resolution = $resolution"
    echo "output = $output"
    echo "gray = $gray"
    echo "multiple = $multiple"
fi

date=$(date '+%Y-%m-%d-%H-%M-%S')

if [ "$multiple" = true ]; then
    continue=true
    page_cnt=0
    while [ "$continue" = true ]; do
        page_cnt=$((page_cnt+1))
        echo "Scanning page $page_cnt"
        scan_pdf /tmp/scan_${date}_${page_cnt}.pdf
        echo "Scan page $page_cnt complete"

        read -p "Scan another page ? (y/n) : " continue
        if [ "$continue" = "n" ]; then
            continue=false
            break
        else
            continue=true
        fi
    done

    cmd=(pdftk /tmp/scan_${date}_*.pdf cat output /tmp/scan_${date}.pdf)
    if [ "$debug" = true ]; then
        echo "${cmd[*]}"
    fi
    ${cmd[@]}

    cmd=(ps2pdf /tmp/scan_${date}.pdf $output)
    if [ "$debug" = true ]; then
        echo "${cmd[*]}"
    fi
    ${cmd[@]}

    echo "Scan complete ($page_cnt pages). Output = $output"
else
    scan_pdf $output
    echo "Scan complete. Output = $output"
fi

